siteName: Clan Drones
siteDesc: This is Clan Drones site, come take a look
author:
  name: Zero
  site: https://floresbenavides.com buy me a coffe
siteUrl: https://clandrones.com
cname: clandrones.com
pages:  # this node is optional
  Miembros: /miembros
  Entradas: /entradas
  Acerca-de-nosotros: /acerca-de-nosotros
  NOM-107: /NOM-107-SCT3-2019
