siteName: Clan Drones
siteDesc: Somos un grupo de entuciastas de los drones con la finalidad de compartir conocimientos y experiencias.
author:
  name: Zero
  site: https://floresbenavides.com buy me a coffe
siteUrl: https://clandrones.com
cname: clandrones.com
pages:  # this node is optional
  Miembros: /miembros
  Entradas: /entradas
  Acerca-de-nosotros: /acerca-de-nosotros
  Mercancía: /mercancia
  Código-de-conducta: /codigo-de-conducta
  NOM-107: /NOM-107-SCT3-2019
